services:
  flask-app:
    image: flask-app  
    container_name: flask-app-container
    ports:
      - "8080:5000"    
  
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app  
