# Python Stage
# apt => upt-get
apt-get update
apt-get upgrade -y
apt-get install -y python3.7 python3-pip
python3 --version

# Specifying a Dir
mkdir flask-app
cd flask-app

# Git Stage (ONLY inside the container)
apt-get install -y git
git clone https://github.com/meldafrawi/basic-flask-app.git .

python3.7 -m pip install -r requirements.txt

# Running Stage
python3 routes.py

